# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import publishers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=2048, unique=True)),
                ('name', publishers.models.TextFieldSingleLine(unique=True)),
                ('links', models.ManyToManyField(blank=True, related_name='publishers', to='links.Link')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
