# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import papers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('journals', '0001_initial'),
        ('links', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(max_length=2048, unique=True, verbose_name='Slug')),
                ('title', papers.models.SingleLineTextField(unique=True, verbose_name='Title')),
                ('volume', papers.models.SingleLineTextField(blank=True, null=True, verbose_name='Volume')),
                ('publishing_date', models.DateField(blank=True, null=True, verbose_name='Publishing date')),
                ('bibtex', models.TextField(blank=True, null=True, verbose_name='BibTex')),
                ('authors', models.ManyToManyField(blank=True, related_name='papers', to='persons.Person', verbose_name='Authors')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='journals.Journal', verbose_name='Journal')),
                ('languages', models.ManyToManyField(blank=True, related_name='papers', to='languages.Language', verbose_name='Languages')),
                ('links', models.ManyToManyField(blank=True, related_name='papers', to='links.Link', verbose_name='Links')),
            ],
            options={
                'ordering': ('journal__name', 'volume', 'title'),
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together=set([('journal', 'volume')]),
        ),
    ]
