# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import papers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
        ('persons', '0001_initial'),
        ('journals', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=2048, unique=True)),
                ('title', papers.models.TextFieldSingleLine(unique=True)),
                ('volume', papers.models.TextFieldSingleLine(blank=True, null=True)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='papers', to='persons.Person')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='journals.Journal')),
                ('languages', models.ManyToManyField(blank=True, related_name='papers', to='languages.Language')),
                ('links', models.ManyToManyField(blank=True, related_name='papers', to='links.Link')),
            ],
            options={
                'verbose_name': ' paper',
                'ordering': ('authors__last_name', 'authors__first_name', 'title'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together=set([('journal', 'volume')]),
        ),
    ]
