# -*- coding: utf-8 -*-
"""
Django settings for bibliothek project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import math
import os

from configparser import RawConfigParser
from gi.repository import GLib


__author__ = 'jnphilipp'
__email__ = 'me@jnphilipp.org'
__license__ = 'GPLv3'
__version__ = '0.0.1'


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# general app info
APP_IDENTIFIER = 'bibliothek'
APP_NAME = 'bibliothek'
APP_COMMENTS = ''
APP_COPYRIGHT = 'Copyright (C) 2016 jnphilipp'
APP_WEBSITE = ''
APP_VERSION = (('#####################################################\n' +
                '#                    bibliothek                     #\n' +
                '#                                                   #\n' +
                '#%sv%s%s#\n' % (' ' * math.floor((50 - len(__version__)) / 2), __version__, ' ' * math.ceil((50 - len(__version__)) / 2)) +
                '#%s%s%s#\n' % (' ' * math.floor((51 - len(__license__)) / 2), __license__, ' ' * math.ceil((51 - len(__license__)) / 2)) +
                '#                                                   #\n'
                '#%s%s%s#\n' % (' ' * math.floor((51 - len(__author__)) / 2), __author__, ' ' * math.ceil((51 - len(__author__)) / 2)) +
                '#%s%s%s#\n' % (' ' * math.floor((51 - len(__email__)) / 2), __email__, ' ' * math.ceil((51 - len(__email__)) / 2)) +
                '#                                                   #\n' +
                '#%s%s%s#\n' % (' ' * math.floor((51 - len(APP_WEBSITE)) / 2), APP_WEBSITE, ' ' * math.ceil((51 - len(APP_WEBSITE)) / 2)) +
                '#####################################################'))
APP_LICENSE = (('This program is free software: you can redistribute it and/or modify\n'+
'it under the terms of the GNU General Public License as published by\n'+
'the Free Software Foundation, either version 3 of the License, or\n'+
'(at your option) any later version.\n'+
'\n'+
'This program is distributed in the hope that it will be useful,\n'+
'but WITHOUT ANY WARRANTY; without even the implied warranty of\n'+
'MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n'+
'GNU General Public License for more details.\n'+
'\n'+
'You should have received a copy of the GNU General Public License\n'+
'along with this program.  If not, see <http://www.gnu.org/licenses/>.'))
APP_AUTHORS = ['jnphilipp <me@jnphilipp.org>']
APP_DOCUMENTERS = ['jnphilipp <me@jnphilipp.org>']


# XDG config
XDG_CONFIG_DIR = GLib.get_user_config_dir()
APP_CONFIG_DIR = os.path.join(XDG_CONFIG_DIR, APP_IDENTIFIER)


# XDG cache
XDG_CACHE_DIR = GLib.get_user_cache_dir()
APP_CACHE_DIR = os.path.join(XDG_CACHE_DIR, APP_IDENTIFIER)


# XDG data
XDG_DATA_DIR = GLib.get_user_data_dir()
APP_DATA_DIR = os.path.join(XDG_DATA_DIR, APP_IDENTIFIER)


config = RawConfigParser()
config.optionxform = str
config.read(os.path.join(APP_CONFIG_DIR, 'config'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.get('secrets', 'SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DEVELOPMENT = False

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'bibliothek',
    'bindings',
    'books',
    'django_bootstrap3',
    'files',
    'genres',
    'journals',
    'languages',
    'links',
    'magazines',
    'papers',
    'persons',
    'publishers',
    'series',
    'shelves',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bibliothek.urls'


# Templates

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR if DEVELOPMENT else APP_DATA_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = config.get('i18n', 'LANGUAGE_CODE', fallback='en-us')

TIME_ZONE = config.get('i18n', 'TIME_ZONE', fallback='UTC')

USE_I18N = config.getboolean('i18n', 'USE_I18N', fallback=True)

USE_L10N = config.getboolean('i18n', 'USE_L10N', fallback=True)

USE_TZ = config.getboolean('i18n', 'USE_TZ', fallback=True)


# Locale messag files for translation
# https://docs.djangoproject.com/en/1.8/topics/i18n/translation/

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)


# Media files

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') if DEVELOPMENT else APP_DATA_DIR


# Shelves app

CURRENCY_SYMBOL = config.get('shelves', 'CURRENCY_SYMBOL', fallback=None)
