# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import series.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=2048, unique=True)),
                ('name', series.models.TextFieldSingleLine(unique=True)),
                ('links', models.ManyToManyField(blank=True, related_name='series', to='links.Link')),
            ],
            options={
                'verbose_name': 'Series',
                'ordering': ('name',),
                'verbose_name_plural': 'Series',
            },
        ),
    ]
