# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 11:18
from __future__ import unicode_literals

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bindings', '0001_initial'),
        ('languages', '0001_initial'),
        ('publishers', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternate_title', books.models.TextFieldSingleLine(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='files')),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='bindings.Binding')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='books.Book')),
                ('languages', models.ManyToManyField(blank=True, related_name='editions', to='languages.Language')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='publishers.Publisher')),
            ],
            options={
                'verbose_name_plural': 'Editions',
                'verbose_name': 'Edition',
                'ordering': ('book', 'published_on'),
            },
        ),
    ]
