# Generated by Django 2.0.7 on 2018-07-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('books', '0002_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='editions', to='links.Link', verbose_name='Links'),
        ),
    ]
