# Generated by Django 4.0.6 on 2022-10-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_edition_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="edition",
            field=models.TextField(blank=True, null=True, verbose_name="Edition"),
        ),
    ]
