# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('link', models.URLField(max_length=4096, unique=True, verbose_name='Link')),
            ],
            options={
                'ordering': ('link',),
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
