# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 10:30
from __future__ import unicode_literals

import bibliothek.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(max_length=2048, unique=True, verbose_name='Slug')),
                ('first_name', bibliothek.fields.SingleLineTextField(verbose_name='First name')),
                ('last_name', bibliothek.fields.SingleLineTextField(blank=True, null=True, verbose_name='Last name')),
                ('links', models.ManyToManyField(blank=True, related_name='persons', to='links.Link', verbose_name='Links')),
            ],
            options={
                'verbose_name_plural': 'Persons',
                'verbose_name': 'Person',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('last_name', 'first_name')]),
        ),
    ]
