# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 10:22
from __future__ import unicode_literals

import bindings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=2048, unique=True)),
                ('name', bindings.models.TextFieldSingleLine(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Bindings',
                'ordering': ('name',),
                'verbose_name': 'Binding',
            },
        ),
    ]
