# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import magazines.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(max_length=2048, unique=True, verbose_name='Slug')),
                ('name', magazines.models.TextFieldSingleLine(unique=True, verbose_name='Name')),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magazine_feed', to='links.Link', verbose_name='Feed')),
                ('links', models.ManyToManyField(blank=True, related_name='magazines', to='links.Link', verbose_name='Links')),
            ],
            options={
                'verbose_name': 'Magazine',
                'ordering': ('name',),
                'verbose_name_plural': 'Magazines',
            },
        ),
    ]
