# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import magazines.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=2048, unique=True)),
                ('name', magazines.models.TextFieldSingleLine(unique=True)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magazine_feed', to='links.Link')),
                ('links', models.ManyToManyField(blank=True, related_name='magazines', to='links.Link')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
