# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import magazines.models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('links', '0001_initial'),
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('issue', magazines.models.TextFieldSingleLine(verbose_name='Issue')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='Published on')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='files', verbose_name='Cover image')),
                ('languages', models.ManyToManyField(blank=True, related_name='issues', to='languages.Language', verbose_name='Languages')),
                ('links', models.ManyToManyField(blank=True, related_name='issues', to='links.Link', verbose_name='Links')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='magazines.Magazine', verbose_name='Magazine')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ('magazine', 'issue'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set([('magazine', 'issue')]),
        ),
    ]
