name: Tests

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      - uses: psf/black@stable
      - name: Flake8
        run: |
          python -m pip install flake8
          flake8 . --extend-exclude="migrations/,tests/" --max-line-length=88 --extend-ignore=E203 --count --statistics
      - name: mypy
        run: |
          python -m pip install mypy
          mypy . --ignore-missing-imports --exclude migrations/
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        django-version: ["3.2", "4.0", "4.1"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
          python -m pip install --upgrade pip wheel
          python -m pip install pycairo PyGObject
          pip install $(grep -v '^ *#\|^Django' requirements.txt | grep .)
          pip install Django~=${{ matrix.django-version }}
      - name: Run Tests
        run: make test
