# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import languages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=2048, unique=True)),
                ('name', languages.models.TextFieldSingleLine(unique=True)),
            ],
            options={
                'verbose_name': ' language',
                'ordering': ('name',),
            },
        ),
    ]
